### PR TITLE
HW-590, add task to remove zmq and msgpack package

### PR DESCRIPTION
**Pull request by zhangjustin**
## Summary of changes

1. Add task to remove zmq and msgpack packages

## How to Test

Will test in ansible playbook

/fyi:  @mark-juwai , @tjoelsson : Please review.

### CODE REVIEW

**Comment by tjoelsson** [comment]
I don't think this is necessary. The git module will checkout the right version.

**Comment by zhangjustin** [comment]
> I don't think this is necessary. The git module will checkout the right version.

No, it will happened will you try to upgrade from php7.1 to php7.3, if you don't delete the old version zmq and msgpack.

**Comment by zhangjustin** [comment]
Can't reproduce the issue, close the PR.

**Comment by zhangjustin** [comment]
Command:
```
https://github.com/juwai/ansible-role-php-zerorpc/blob/master/tasks/main.yml#L30

**Comment by zhangjustin** [comment]
https://github.com/juwai/ansible-role-php-zerorpc/blob/master/tasks/main.yml#L30
Command will  generate some file, when you upgrade from php7.1 to php7.3 in old container,  the command will not generate new file to install zmq and msgpack, even install succeed, but not compatible with php7.3

**Comment by tjoelsson** [comment]
We don't want to recompile ~~zerorpc~~ zmq extension every time playbook runs

**Comment by mark-juwai** [comment]
```
dest: "~/php-zmq-{{ zmq_source_version }}"
```
instead of:
```
dest: "~/php-zmq"
```
?

**Comment by tjoelsson** [comment]
That's better. I guess it will still compile, but we can avoid downloading the code each time.

**Comment by zhangjustin** [comment]
Ok, also i don't want update zmq and msgpack in this role, we can update update in application repo

**Review by mark-juwai — DISMISSED** [review]

**Review by mark-juwai — APPROVED** [review]

**Review by tjoelsson — APPROVED** [review]

**Pull request merged**
